### ISSUE TITLE
OTP-21 compatibility

### ISSUE THREAD

**Issue by ypaq** [ninenines/ct_helper#6]
Library uses `random` module and `crypto:rand_uniform`.

**Comment by ypaq** [comment]
Only when you enable warnings as errors ;)

**Comment by essen** [comment]
Yeah but I mean when used with erlang.mk as a dep it's not a problem because erlang.mk disables them for deps. Do you run in an issue because of a different environment or scenario?

**Comment by ypaq** [comment]
The infrastructure I work with depends heavily on rebar3.

**Comment by essen** [comment]
Then you probably need to add `app:: rebar.config` at the end of the Makefile in ct_helper and that'll disable warnings as errors for rebar. You'll need to rebuild and commit the rebar.config file it generates. PR welcome once you confirm it works.

**Comment by ypaq** [comment]
Thanks, I'll look into it. Just out of curiosity, are you against updating the code?

**Comment by essen** [comment]
I have to make it work for 18+.

**Comment by essen** [comment]
I've committed a blank rebar.config to fix this.
